# Generated by Django 5.0.7 on 2024-08-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbook",
            options={"verbose_name": "На руках", "verbose_name_plural": "На руках"},
        ),
        migrations.AddField(
            model_name="userbook",
            name="returned_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
