# Generated by Django 5.0.7 on 2024-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userbook_options_userbook_returned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbook",
            name="returned_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
