# Generated by Django 5.0.7 on 2024-08-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_userbook_returned_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbook",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
